server:
  port: 0
  servlet:
    context-path: /api/v1

spring:
  application:
    name: careflow-backend-test

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/careflow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000
  refresh-expiration: 8640000

careflow:
  storage:
    path: ./target/test-uploads
  maps:
    api-key: MOCK_MAPS_KEY_TEST
